### ISSUE TITLE
existing directory

### ISSUE THREAD

**Issue by EmilienM** [depends-on/depends-on-action#26]
I would like `depends-on` to work on a directory that I'm giving.

Example:
Some projects like to create a dedicated directory for running tests, so when we `go geŧ`, the `go.sum` is not polluted.

```yaml
      - name: Setup environment
        run: |
          # Changing into a different directory to avoid polluting go.sum with "go get"
          cd "$(mktemp -d)"
          go mod init unit_tests

          # Pin to a version that Go v1.15 supports
          go get golang.org/x/tools/cmd/goimports@v0.8.0
```

Right now, `depends-on` will create a local directory with the project name and make edits into the `go.mod`.
I want to be able to provide a directory (e.g. `/tmp/repo_for_tests`) where I'll run the tests from and where I want my dependencies to be updated.
